---

- name: Load nginx packer variables
  ansible.builtin.include_vars:
    file: ../../../../packer_ami/nginx/packer_vars.yaml
  #register: packer_vars

- name: Print loaded packer variables
  ansible.builtin.debug:
    var: packer_vars


- name: Load nginx  variables
  ansible.builtin.include_vars:
    file: ../packer_ami/nginx/nginx.yaml
  #register: nginx

- name: Clean up
  ansible.builtin.file:
    path: '{{ playbook_dir }}/{{ del_dir }}'
    state: absent
  with_items:
   - post-playbooks
  loop_control:
    loop_var: del_dir

- name: Create Post-Config Directory
  ansible.builtin.file:
    path: '{{ playbook_dir }}/{{ dir }}'
    state: directory
  with_items:
   - post-playbooks
  loop_control:
    loop_var: dir

- name: Check if template file exist
  ansible.builtin.stat:
    path: ../packer_ami/nginx/templates/{{ product }}_install.yaml.j2
  register: template_file

- name: Create files from templates
  ansible.builtin.template:
    src: '../templates/{{ file }}.j2'
    dest: '{{ playbook_dir }}/post-playbooks/{{ file }}'
    mode: '0644'
  loop:
    - vm.json
   # - vars.yaml
  loop_control:
    loop_var: file
- name: Create file from template
  template:
    src: '../packer_ami/nginx/templates/{{ product }}_install.yaml.j2'
    dest: '{{ playbook_dir }}/{{ product }}_install.yaml'
    mode: '0644'
  when: template_file.stat.exists

- name: Run packer init
  ansible.builtin.command: /usr/bin/packer init {{ playbook_dir }}/post-playbooks/vm.json
  register: packer_init
  failed_when: packer_init.rc | int > 0
  changed_when: packer_init.rc | int == 0
  ignore_errors: true

- name: Run packer build
  ansible.builtin.command: /usr/bin/packer build {{ playbook_dir }}/post-playbooks/vm.json
  register: packer_st
  failed_when: packer_st.rc | int > 0
  changed_when: packer_st.rc | int == 0
  ignore_errors: true
