# Load common variables
---
- name: "Load {{ product }} product-specific variables if present"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "../../../vars/{{ product }}/global.yml"
      skip: True


- name: "Load {{ envir }} environment-specific variables if present"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "../../../vars/{{ product }}/{{ envir }}/global.yml"
      skip: True

      
- name: "Load {{ instance_name }} instance-specific variables if present"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "../../../vars/{{ product }}/{{ envir }}/{{ instance_name }}.yml"
      skip: True