---
- name: Run packer
  gather_facts: true
  hosts: localhost
  #vars_files:
  #  - ../packer_ami/nginx/packer_vars.yaml
  tasks:
    #- name: Print variables
    #  ansible.builtin.debug:
    #      var: packer_vars

    - name: Include Role
      ansible.builtin.include_role:
        name: nginx_linux
